import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextThemesProvider } from '@/components/theme/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Viktor Filyk',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={inter.className + ' container mx-auto max-w-3xl p-4'}>
        <NextThemesProvider>{children}</NextThemesProvider>
      </body>
    </html>
  )
}
