import './globals.css'
// import "@code-hike/mdx/dist/index.css"
// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

export default function Layout({ children }: React.PropsWithChildren<{}>) {
  return (
    <>
      // MAIN LAYOUT
      {children}
      // MAIN LAYOUT
    </>
  )
}
